server:
  port: 7001
spring:
  application:
    name: cloud-p-hystrix-svr

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka