server:
  port: 1001

spring:
  application:
    name: seata-account-service
#  cloud:
#    alibaba:
#      seata:
#        tx-service-group: SEATA_GROUP
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Hongkong
    username: root
    password: 123456

feign:
  hystrix:
    enabled: false

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapperLocations: classpath:mybatis/mapper/*.xml

seata:
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group : "SEATA_GROUP"
      namespace: ""
      username: "nacos"
      password: "nacos"
  tx-service-group: my_test_tx_group
