server:
  port: 6001
eureka:
  instance:
    hostname: eureka6001.com
  client:
    register-with-eureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka6002.com:6002/eureka/